spring:
  profiles:
    active: dev

# mybatis-plus配置
mybatis-plus:
  # mapper文件位置
  mapper-locations:
    - classpath:**/*.xml

# spring-doc配置
springdoc:
  # 默认开启@ParamterObject注解
  default-flat-param-object: true